'use client';

import { useState } from 'react';
import { PageHeader } from '@/components/layout/PageHeader';
import { deceptionFiles } from '@/data/adaptations';
import {
  Folder, FolderOpen, FileText, Key, Network, Globe, Server,
  ShieldAlert, Lock, Database, CheckCircle,
} from 'lucide-react';

export default function DeceptionLabPage() {
  const [activeTab, setActiveTab] = useState<'files' | 'credentials' | 'services' | 'network' | 'web'>('files');
  const [selectedFile, setSelectedFile] = useState({
    name: 'database.conf',
    path: '/home/admin/database.conf',
    reason: 'Targeted because attacker showed database interest.',
    content: `[database]\nhost = 10.0.1.50\nport = 3306\nuser = app_admin\npassword = {{HONEYTOKEN_CANARY_DB_PASS}}\ndbname = production_orders`,
  });

  const tabs = [
    { id: 'files' as const, label: 'Filesystem Decoys', icon: Folder },
    { id: 'credentials' as const, label: 'Honeytokens', icon: Key },
    { id: 'services' as const, label: 'Services', icon: Server },
    { id: 'network' as const, label: 'Topology', icon: Network },
    { id: 'web' as const, label: 'Web Traps', icon: Globe },
  ];

  return (
    <div className="space-y-6">
      <PageHeader title="Dynamic Deception" subtitle="Observe the synthetic environment presented to the adversary.">
        <div className="flex items-center gap-2 px-3 py-1 rounded-lg bg-amber-500/10 border border-amber-500/20 text-xs text-amber-400 font-mono">
          <span className="w-2 h-2 rounded-full bg-amber-400" style={{ animation: 'pulse-glow 2s ease-in-out infinite' }} />
          Trap Mode: Active
        </div>
      </PageHeader>
      <div className="p-3.5 rounded-xl bg-stone-200/70 border border-stone-300 flex items-center justify-between text-xs">
        <div className="flex items-center gap-2.5 text-stone-600">
          <ShieldAlert className="w-4 h-4 text-amber-400 shrink-0" />
          <span>All items are synthetic decoys with canary honeytokens. No real credentials are exposed.</span>
        </div>
      </div>
      <div className="flex items-center gap-2 border-b border-stone-300 pb-1 overflow-x-auto">
        {tabs.map((tab) => {
          const Icon = tab.icon;
          const isActive = activeTab === tab.id;
          return (
            <button key={tab.id} onClick={() => setActiveTab(tab.id)}
              className={`flex items-center gap-2 px-4 py-2 text-xs font-semibold rounded-t-lg transition-all border-b-2 whitespace-nowrap ${
                isActive ? 'border-amber-500 text-amber-400 bg-amber-500/5' : 'border-transparent text-stone-600 hover:text-stone-700'
              }`}>
              <Icon className="w-3.5 h-3.5" /><span>{tab.label}</span>
            </button>
          );
        })}
      </div>
      {activeTab === 'files' && (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          <div className="lg:col-span-5 card-interactive p-5 space-y-4">
            <div className="flex items-center justify-between pb-3 border-b-honey-border">
              <span className="text-xs font-bold text-stone-800 uppercase tracking-wider">Synthetic Filesystem Tree</span>
              <span className="text-[10px] text-amber-400 font-mono">Auto-seeded</span>
            </div>
            <div className="font-mono text-xs space-y-2">
              {[
                { name: 'backup.sh', icon: FileText, color: 'cyan', label: 'Script decoy' },
                { name: 'database.conf', icon: Database, color: 'emerald', label: 'DB credential honeytrap' },
                { name: 'passwords.txt', icon: Lock, color: 'purple', label: 'Credential harvest decoy' },
                { name: 'employee_data.csv', icon: FileText, color: 'amber', label: 'PII canary trap' },
              ].map((file) => (
                <button key={file.name} onClick={() => setSelectedFile({ name: file.name, path: `/home/admin/${file.name}`, reason: file.label, content: `# ${file.name}\n# Decoy generated by Evolution Engine` })}
                  className={`w-full text-left p-2 rounded flex items-center justify-between transition-colors ${selectedFile.name === file.name ? 'bg-stone-200 text-amber-400' : 'hover:bg-stone-200/50 text-stone-600'}`}>
                  <span className="flex items-center gap-1.5 truncate"><file.icon className="w-3.5 h-3.5" />{file.name}</span>
                  <span className="text-[10px] text-amber-400 bg-amber-500/10 px-1.5 py-0.5 rounded border border-amber-500/20">Decoy</span>
                </button>
              ))}
            </div>
          </div>
          <div className="lg:col-span-7 card-interactive p-5 flex flex-col space-y-4 font-mono">
            <div className="pb-3 border-b-honey-border">
              <span className="text-xs font-bold text-stone-800">{selectedFile.path}</span>
              <div className="text-[11px] text-amber-400 mt-0.5">● {selectedFile.reason}</div>
            </div>
            <div className="mt-4 p-4 rounded-xl bg-stone-50 border border-stone-300/80 text-xs leading-relaxed text-stone-400 whitespace-pre-wrap overflow-x-auto">{selectedFile.content}</div>
            <div className="pt-3 border-t-honey-border text-xs text-stone-600 flex items-center justify-between font-sans">
              <span>Sensor Watermark: Attached</span>
              <span className="text-amber-400 font-semibold flex items-center gap-1"><CheckCircle className="w-3.5 h-3.5" />Beacon will alert SOC</span>
            </div>
          </div>
        </div>
      )}
      {activeTab === 'credentials' && (
        <div className="card-interactive p-6 space-y-4">
          <h3 className="text-sm font-bold text-stone-800">Active Canary Honeytokens</h3>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 pt-2">
            {[
              { name: 'AWS_ACCESS_KEY_ID', value: 'AKIAIOSFODNN7EXAMPLE', color: 'emerald' },
              { name: 'MYSQL_ROOT_HASH', value: '$6$salt$canary_hash_beacon', color: 'purple' },
              { name: 'SSH_PRIVATE_KEY', value: 'id_rsa (Trap Beacon 4096)', color: 'amber' },
            ].map((cred) => (
              <div key={cred.name} className="p-4 rounded-xl bg-stone-200/60 border border-stone-300 space-y-2">
                <div className="flex items-center justify-between"><span className="text-xs font-bold text-stone-800 font-mono">{cred.name}</span><span className="text-[10px] px-2 py-0.5 rounded bg-amber-500/10 text-amber-400 border border-amber-500/20">Canary Live</span></div>
                <p className="font-mono text-xs text-blue-400 truncate">{cred.value}</p>
                <p className="text-[11px] text-stone-600">Seeded with tracking beacon</p>
              </div>
            ))}
          </div>
        </div>
      )}
      {activeTab === 'services' && (
        <div className="card-interactive p-6 space-y-4">
          <h3 className="text-sm font-bold text-stone-800">Emulated Synthetic Daemon Ports</h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 pt-2">
            {[
              { port: 22, name: 'OpenSSH 8.9p1', interactions: 142 },
              { port: 80, name: 'Apache httpd 2.4.52', interactions: 89 },
              { port: 3306, name: 'MySQL Community 8.0.32', interactions: 48 },
              { port: 6379, name: 'Redis Server 7.0.5', interactions: 26 },
            ].map((svc) => (
              <div key={svc.port} className="p-4 rounded-xl bg-stone-200/50 border border-stone-300">
                <div className="flex items-center justify-between mb-1"><span className="text-sm font-bold text-amber-400 font-mono">Port {svc.port}</span><span className="text-[10px] text-amber-400 bg-amber-500/10 px-1.5 py-0.2 rounded border border-amber-500/20">Active</span></div>
                <div className="text-xs text-stone-400 mt-1">{svc.name}</div>
                <div className="text-[11px] text-stone-600 mt-2">Captured: {svc.interactions} probes</div>
              </div>
            ))}
          </div>
        </div>
      )}
      {activeTab === 'network' && (
        <div className="card-interactive p-6 space-y-4">
          <h3 className="text-sm font-bold text-stone-800">Virtual Honeynet Topology</h3>
          <div className="p-4 rounded-xl bg-stone-200/40 border border-stone-300 font-mono text-xs space-y-2 text-stone-600">
            <div className="text-blue-400 font-bold">10.0.1.0/24 — DMZ Honeytrap Subnet</div>
            <div className="pl-4">├── 10.0.1.10 (SSH-HNY-01 — Linux Decoy)</div>
            <div className="pl-4">└── 10.0.1.50 (DB-HNY-01 — Target Honeytrap)</div>
            <div className="text-orange-400 font-bold pt-2">10.0.2.0/24 — Synthetic Enterprise (Airgapped)</div>
          </div>
        </div>
      )}
      {activeTab === 'web' && (
        <div className="card-interactive p-6 space-y-4">
          <h3 className="text-sm font-bold text-stone-800">Synthetic Web Decoy Portals</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-2">
            <div className="p-4 rounded-xl bg-stone-200/50 border border-stone-300 space-y-2">
              <span className="text-xs font-bold text-blue-400 font-mono">/admin/portal (SSO Login Trap)</span>
              <p className="text-xs text-stone-600">Logs username lists and password spraying attempts.</p>
              <div className="text-[11px] text-amber-400">Captured: 400+ brute force payloads today</div>
            </div>
            <div className="p-4 rounded-xl bg-stone-200/50 border border-stone-300 space-y-2">
              <span className="text-xs font-bold text-orange-400 font-mono">/api/v1/customers/export (Data Trap)</span>
              <p className="text-xs text-stone-600">Synthetically generated CSV with canary tokens.</p>
              <div className="text-[11px] text-amber-400">Canary trigger rate: 100% telemetry fidelity</div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
